law_dict= {'Civil Rights and criminal division': ['division',
  'victim',
  'police',
  'officers',
  'law',
  'attorney',
  'justice',
  'department',
  'civil',
  'rights'],
           
'National security': ['fbi',
  'states',
  'office',
  'united',
  'fraud',
  'indictment',
  'department',
  'criminal',
  'district',
  'attorney'],

'civil and health care division':['beneficiaries',
  'home',
  'strike',
  'oig',
  'services',
  'care',
  'hhs',
  'fraud',
  'health',
  'medicare'],

 'Anti trust and Property':['division',
  'foreclosure',
  'mortgage',
  'task',
  'rigging',
  'bid',
  'auctions',
  'fraud',
  'financial',
  'antitrust'],

 'tax and anti trust':['banks',
  'undeclared',
  'offshore',
  'ubs',
  'irs',
  'account',
  'tax',
  'swiss',
  'bank',
  'accounts'], 

 'health care division':['patients',
  'medicaid',
  'fraud',
  'services',
  'false',
  'settlement',
  'medicare',
  'claims',
  'care',
  'health'],

 'civil rights':['department',
  'civil',
  'lawsuit',
  'rights',
  'act',
  'disabilities',
  'hud',
  'discrimination',
  'fair',
  'housing'], 

'Environment and natural resources':['environment',
  'act',
  'pollution',
  'oil',
  'clean',
  'air',
  'water',
  'environmental',
  'epa',
  'settlement'],

 'Tax Division':['prepared',
  'preparing',
  'return',
  'irs',
  'income',
  'injunction',
  'complaint',
  'customers',
  'returns',
  'tax'],

 ' national security and civil Rights':['hotline',
  'provision',
  'status',
  '800',
  'citizenship',
  'immigration',
  'ina',
  'employment',
  'discrimination',
  'osc'],
 
 
 'tax division':['revenue',
  'division',
  'refunds',
  'taxes',
  'attorney',
  'false',
  'income',
  'returns',
  'irs',
  'tax'], 

 'child/ exploitation, Child exploitation and obscenity section':['images',
  'sexual',
  'children',
  'ceos',
  'safe',
  'project',
  'exploitation',
  'childhood',
  'pornography',
  'child'],

  'Criminal Division' : ['county',
  'police',
  'ms',
  'texas',
  'abt',
  'aka',
  'murder',
  'racketeering',
  'members',
  'gang'],

  "Office of attorny and Election Division": ['act',
  'department',
  '514',
  'agreement',
  'access',
  'election',
  'rights',
  'disabilities',
  'voting',
  'ada']
 }